// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7St4k95aMMMeHILedglLhmyCXPAWOlck',
    appId: '1:264285638482:web:0d49a84c1d22df5b71b48b',
    messagingSenderId: '264285638482',
    projectId: 'zuro-a3cd2',
    authDomain: 'zuro-a3cd2.firebaseapp.com',
    storageBucket: 'zuro-a3cd2.firebasestorage.app',
    measurementId: 'G-71CXCT89V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd3DS32iPmD38ezZvwxn9jjrLCvuZe3B8',
    appId: '1:264285638482:android:07604805a1fd8c4471b48b',
    messagingSenderId: '264285638482',
    projectId: 'zuro-a3cd2',
    storageBucket: 'zuro-a3cd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArCff4lL2OgRw3GeNJdKtI9LSitTF575w',
    appId: '1:264285638482:ios:acd0cd17b020f74871b48b',
    messagingSenderId: '264285638482',
    projectId: 'zuro-a3cd2',
    storageBucket: 'zuro-a3cd2.firebasestorage.app',
    iosBundleId: 'com.example.zuro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArCff4lL2OgRw3GeNJdKtI9LSitTF575w',
    appId: '1:264285638482:ios:acd0cd17b020f74871b48b',
    messagingSenderId: '264285638482',
    projectId: 'zuro-a3cd2',
    storageBucket: 'zuro-a3cd2.firebasestorage.app',
    iosBundleId: 'com.example.zuro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7St4k95aMMMeHILedglLhmyCXPAWOlck',
    appId: '1:264285638482:web:99240c7b25bb957371b48b',
    messagingSenderId: '264285638482',
    projectId: 'zuro-a3cd2',
    authDomain: 'zuro-a3cd2.firebaseapp.com',
    storageBucket: 'zuro-a3cd2.firebasestorage.app',
    measurementId: 'G-WPDM8M14YS',
  );
}
